# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Optionally build your docs in additional formats such as PDF
# formats:
#   - pdf

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: Docs/sphinx-source/conf.py

######################################################################
# Option 1: Use mamba
build:
  os: ubuntu-22.04
  tools:
    # python: "3.11"
    python: "mambaforge-22.9"
#  apt_packages:
#    - libcairo2-dev
#    - libpango1.0-dev
#    - ffmpeg

conda:
  environment: anaconda-project.yaml

# Optionally set the version of Python and requirements required to build your docs
python:
   version: "3.10"
   install:
    - requirements: requirements.doc.txt
