name: _super_hydro
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3
  - ipykernel
  - configargparse
  - cython
  - scipy
  - matplotlib
  - pyzmq
  - attrs
  - zope.interface

  # For performance
  - numexpr
  
  - pip
  - pip:
    - kivy
