name: _super_hydro_server_gpu
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3
  - configargparse
  - scipy
  - matplotlib
  - pyzmq
  - attrs
  - IPykernel
  - numba
  - notebook
  - cython
  - reikna    # FFT for CUDA etc.
  - pip:
    - pycuda
    - mmfutils
    - mmf_setup
