name: super_hydro
channels:
  - defaults
  - conda-forge
  - mforbes
dependencies:
  # Clients and Servers
  - python>=3
  - configargparse
  - numpy
  - pyzmq
  - zope.interface
  - matplotlib
  
  # Server
  - scipy

  # For performance
  - numexpr
  #- cython

  # Notebook Client
  - ipykernel
  - ipywidgets
  - pillow
  - mmf_setup
  #- mmfutils
  #- ipympl
  #- husl  

  - pip
  - pip:
    - kivy
    - mmfutils>=0.4.11