name: _super_hydro_server
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3
  - configargparse
  - scipy
  - matplotlib
  - attrs
  - zope.interface
  # For monkey patching
  - eventlet

  # ZMQ Networking
  - pyzmq
  
  # SocketIO Networking
   - python-socketio
   - aiohttp

  # For performance
  - numexpr
  - cython
  - pyfftw

  # For GPU support
  #- cupy
