name: _super_hydro_server
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3
  - configargparse
  - scipy
  - matplotlib
  - pyzmq
  - attrs
  - zope.interface
  - flask
  - flask-socketio
  - gevent-websocket

  # For performance
  - numexpr
  - cython
  - pyfftw

  # For GPU support
  #- cupy
