name: super-hydro
channels:
  - defaults
  - conda-forge
dependencies:
  # Clients and Servers
  - python>=3
  - configargparse
  - numpy
  - pyzmq
  - zope.interface
  - matplotlib
  
  # Server
  - scipy

  # For performance
  - numexpr
  #- cython

  # Notebook Client
  - ipykernel
  - ipywidgets
  - mmf_setup
  - pillow
  
  - pip
  - pip:
    - kivy
