name: _super_hydro_test
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3
  - ipykernel
  - configargparse
  - cython
  - scipy
  - matplotlib
  - pyzmq

  # For testing
  - pytest-flake8
  - pytest-cov
  - pytest-runner

  - pip:
    - kivy
